[config]
log_name = "reader.log"

[database]
database = "chat_reader"
host = "127.0.0.1"
user = "postgres"
password = "1234"
port = "5432"

[telegram]
api_id = 1234567
api_hash = "cxxxxxxcfffffffafgdfgwewer"
